name: Coverage

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

  workflow_dispatch:

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: sudo apt install lcov

      - name: Make
        run: make coverage ARCH=x64 CONFIG=Debug

      - name: Coveralls
        uses: coverallsapp/github-action@v2
