name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  test:
    uses: cgware/action-test/.github/workflows/action.yml@main
